global:
  environment: staging
frontend:
  image:
    repository: rohankhanal14/crud-frontend
    tag: 26-b595da14
  replicaCount: 1
backend:
  image:
    repository: rohankhanal14/crud-backend
    tag: 21-23f87fd9
  replicaCount: 1
  env:
    corsOrigin: http://staging.crud.local
mongodb:
  storage: 5Gi
ingress:
  host: staging.crud.local
